### ISSUE TITLE
Idea/question: would it possible to port some Redis protocol layer code directly

### ISSUE THREAD

**Issue by syang** [yongman/tidis#34]
Problem to solve: make sure 100% Redis API supported

Idea: instead to re-write different API supports, can we port the protocol layer code directly and then use TiKV client code to write the requests to TiKV?

**Comment by yongman** [comment]
Some api will be inefficient according the storage features compare to memory access. eg random commands `RANDOMKEY`.
 
Addition, because of the encoding of the user key, different types will have entire keyspace, such as `set key value` and `lpush key value` have the same key name with different type, so we add `delete` for string, and `ldelete` for list.

Any ideas will be welcomed.

**Comment by syang** [comment]
@yongman I am thinking of using ScyllaDB as a Redis backend (just as your project here using TiKV as Redis backend), and I wonder how much I can reuse from this project. 

Or could we possibly architect this project in a way that it supports multiple backends? If so, what's the percentage of code can be used here?

Love to brainstorm further.

**Comment by yongman** [comment]
@syang  I am not sure if the client of SycllaDB have the same transaction api, but you can refer to tidis code and try to find a lower cost plan.

**Comment by syang** [comment]
@yongman what do you mean by "transaction api"? can you give one or two examples?

**Comment by syang** [comment]
@yongman ping for the question of "transaction api". thanks.
