### ISSUE TITLE
can multi keys which belong to different region execute successfully in one set command

### ISSUE THREAD

**Issue by jackycchen** [yongman/tidis#37]
can multi keys which belong to different region execute successfully in one set command？
for example:
mset(key1,key2);
key1 belongs to region1, and key2 belongs to region2

**Comment by honeychen502** [comment]
I used java client, I think the behavior of different client, both rpc communications.
tikv call procedure is:
Firstly, create client by specific key's region address;
Secondly, send  commit to tikv, and receive failure result because keys belongs to different region.

Mybe, I have to test again, Thanks !
